name: passanger_helper
description: 'Passanger helper'

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  go_router: ^14.7.2
  get_it: ^8.0.3
  bot_toast: ^4.1.3
  bloc: ^9.0.0
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  fpdart: ^1.1.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
